spring:
  application:
    name: file-server
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port: 8040


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka
file:
  path:
    avatar: C:/static/img/avatar/
  file-type-array: .png,.jpg,.jpeg,.txt,.zip,.rar,.pdf,.xml,.xls,.MP4,.xlsx,.mp3,.wav
  max-file-size: 10000