server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: socket-server
          uri: lb://socket-server
          predicates:
            - Path=/test/**
        # webSocket 协议
        - id: socket-server-ws
          uri: lb:ws://socket-server
          predicates:
            - Path=/live/**
        - id: vmeet-server
          uri: lb://vmeet-server
          predicates:
            - Path=/user/**,/contact/**,/img/**,/static/**
        - id: mail-server
          uri: lb://mail-server
          predicates:
            - Path=/mail/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka