server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: socket-server
          uri: lb://socket-server
          predicates:
            - Path=/test/**,/socket/**
        - id: socket-server-ws
          uri: lb:ws://socket-server
          predicates:
            - Path=/live/**,/chat/**
        - id: vmeet-server
          uri: lb://vmeet-server
          predicates:
            - Path=/user/**,/contact/**,/message/**,/videoCallRecord/**,/img/**,/static/**,/file/**
        - id: mail-server
          uri: lb://mail-server
          predicates:
            - Path=/mail/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka