server:
  port: 8010
spring:
  application:
    name: mail-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///vmeet
    username: root
    password: 123456

  mail:
    host: smtp.qq.com
    username: v_meet@qq.com
    password: sqdmiqhzpoyjcjee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka