server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7500/eureka

datasource:
  url: localhost:3306/vmeet

spring:
  application:
    name: vmeet-server

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#  type-aliases-package: com.vmeetserver.entity

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 64800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

app:
  download-path: C:\Users\admin\Desktop\download\
  upload-path: C:\Users\admin\Desktop\upload\
  file-type-array: .png,.jpg,.jpeg,.txt,.zip,.rar,.pdf,.xml,.xls,.MP4,.xlsx,.mp3,.wav
  max-file-size: 10800000

